-- 1. Usuários e Tokens
CREATE TABLE tbl_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id VARCHAR(255) UNIQUE,
                           name VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           password VARCHAR(255) NOT NULL,
                           role VARCHAR(50),
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP
);

CREATE TABLE tbl_refresh_tokens (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    token VARCHAR(255) NOT NULL UNIQUE,
                                    expiry_date TIMESTAMP NOT NULL,
                                    user_id BIGINT NOT NULL,
                                    FOREIGN KEY (user_id) REFERENCES tbl_users(id)
);

-- 2. Catálogo
CREATE TABLE tbl_categories (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                category_id VARCHAR(255) UNIQUE,
                                name VARCHAR(255) UNIQUE,
                                description VARCHAR(255),
                                created_at TIMESTAMP,
                                updated_at TIMESTAMP,
                                parent_id BIGINT,
                                FOREIGN KEY (parent_id) REFERENCES tbl_categories(id)
);

CREATE TABLE tbl_products (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              product_id VARCHAR(255) NOT NULL UNIQUE,
                              name VARCHAR(255) NOT NULL,
                              description VARCHAR(255),
                              price NUMERIC(10, 2) NOT NULL,
                              sku VARCHAR(255) UNIQUE,
                              cost_price NUMERIC(10, 2),
                              stock_quantity INTEGER,
                              active BOOLEAN DEFAULT TRUE,
                              average_rating DOUBLE DEFAULT 0.0,
                              review_count INTEGER DEFAULT 0,
                              seller_email VARCHAR(255),
                              category_id BIGINT NOT NULL,
                              owner_id BIGINT NOT NULL,
                              created_at TIMESTAMP,
                              updated_at TIMESTAMP,
                              FOREIGN KEY (category_id) REFERENCES tbl_categories(id),
                              FOREIGN KEY (owner_id) REFERENCES tbl_users(id)
);

-- 3. Estoque e Auditoria
CREATE TABLE tbl_inventory_transactions (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            quantity INTEGER NOT NULL,
                                            type VARCHAR(50) NOT NULL,
                                            description VARCHAR(255),
                                            responsible_email VARCHAR(255),
                                            created_at TIMESTAMP,
                                            product_id BIGINT NOT NULL,
                                            FOREIGN KEY (product_id) REFERENCES tbl_products(id)
);

CREATE TABLE tbl_audit_logs (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                action VARCHAR(50) NOT NULL,
                                entity_name VARCHAR(50) NOT NULL,
                                entity_id VARCHAR(255) NOT NULL,
                                old_state VARCHAR(4000),
                                new_state VARCHAR(4000),
                                changed_by VARCHAR(255) NOT NULL,
                                changed_at TIMESTAMP
);

-- 4. Promoções
CREATE TABLE tbl_coupons (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             code VARCHAR(255) NOT NULL UNIQUE,
                             discount_type VARCHAR(50) NOT NULL,
                             discount_value NUMERIC(10, 2) NOT NULL,
                             expiration_date DATE NOT NULL,
                             active BOOLEAN,
                             global_usage_limit INTEGER,
                             current_usage_count INTEGER DEFAULT 0,
                             usage_limit_per_user INTEGER,
                             min_order_value NUMERIC(10, 2),
                             target_category_id VARCHAR(255),
                             target_product_id VARCHAR(255)
);

-- 5. Carrinho
CREATE TABLE tbl_carts (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           updated_at TIMESTAMP,
                           user_id BIGINT UNIQUE,
                           FOREIGN KEY (user_id) REFERENCES tbl_users(id)
);

CREATE TABLE tbl_cart_items (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                quantity INTEGER,
                                cart_id BIGINT,
                                product_id BIGINT,
                                FOREIGN KEY (cart_id) REFERENCES tbl_carts(id),
                                FOREIGN KEY (product_id) REFERENCES tbl_products(id)
);

-- 6. Pedidos e Reviews
CREATE TABLE tbl_orders (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id VARCHAR(255) NOT NULL UNIQUE,
                            status VARCHAR(50) NOT NULL,
                            customer_name VARCHAR(255),
                            phone_number VARCHAR(255),
                            tax NUMERIC(10, 2) NOT NULL,
                            discount NUMERIC(10, 2),
                            grand_total NUMERIC(10, 2) NOT NULL,
                            payment_method VARCHAR(50),
                            applied_coupon VARCHAR(255),
                            payment_status_detail VARCHAR(50),
                            razorpay_order_id VARCHAR(255),
                            razorpay_payment_id VARCHAR(255),
                            razorpay_signature VARCHAR(255),
                            created_at TIMESTAMP,
                            updated_at TIMESTAMP,
                            customer_id BIGINT NOT NULL,
                            FOREIGN KEY (customer_id) REFERENCES tbl_users(id)
);

CREATE TABLE tbl_order_items (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 product_id VARCHAR(255),
                                 name VARCHAR(255),
                                 price NUMERIC(10, 2) NOT NULL,
                                 quantity INTEGER,
                                 order_id BIGINT, -- A coluna de join criada pelo JPA
                                 FOREIGN KEY (order_id) REFERENCES tbl_orders(id)
);

CREATE TABLE tbl_reviews (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             rating INTEGER NOT NULL,
                             comment VARCHAR(500),
                             order_id VARCHAR(255) NOT NULL,
                             created_at TIMESTAMP,
                             user_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             FOREIGN KEY (user_id) REFERENCES tbl_users(id),
                             FOREIGN KEY (product_id) REFERENCES tbl_products(id),
                             UNIQUE (order_id, product_id)
);